server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intikhab
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

security:
  jwt:
    secret-key: 1af01228a69e2340e0706abe0ea8337420dda626d6f1dea5682db22766aa5809
    expiration-time: 3600000
